/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.*;
import javax.swing.*;
import controller.Koneksi;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Asus
 */
public class CheckOut extends javax.swing.JFrame {
  
    Connection conn = Koneksi.getKoneksi();
    ResultSet rs = null;
    PreparedStatement pst = null;

    public void ubahStatus() throws SQLException {
       try {
            String sql = "update kamar set status=? where no_kamar=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, "Not Booking"); // Parameter pertama: status
            pst.setString(2, Cari.getText()); // Parameter kedua: nomor kamar
            int rowsAffected = pst.executeUpdate(); // Menggunakan executeUpdate, bukan executeQuery
            ubahStatusCostumer();
            System.out.println(rowsAffected + " baris berhasil diubah.");
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Berhasil Check Out",
                        "Sukses", JOptionPane.INFORMATION_MESSAGE);
                Home HM = new Home();
                HM.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Gagal melakukan Check Out",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
         } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat melakukan Check Out.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    public void ubahStatusCostumer() throws SQLException {
        String sql = "update customer set status=? where no_kamar=?";
        pst = conn.prepareStatement(sql);
        pst.setString(1, "Sudah"); // Parameter pertama: status
        pst.setString(2, Cari.getText()); // Parameter kedua: nomor kamar
        int rowsAffected = pst.executeUpdate(); // Menggunakan executeUpdate, bukan executeQuery
        System.out.println(rowsAffected + " baris berhasil diubah.");

    }
    /**
     * Creates new form CheckIn
     */
    public CheckOut() {
        initComponents();
//      tanggal.setIndex(cbTipeKamar.getSelectedIndex());
    }
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tKosong = new javax.swing.JTable();
        bCheckOut = new javax.swing.JButton();
        Cari = new javax.swing.JTextField();
        bCari = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1025, 550));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
